# Generated by Django 4.2.5 on 2023-11-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
        migrations.AlterModelTable(
            name='libro',
            table=None,
        ),
    ]
