# Generated by Django 4.2.5 on 2023-11-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_categoria_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='categoria_codigo',
            new_name='categoria',
        ),
    ]
