# Generated by Django 4.2.5 on 2023-11-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
