# Generated by Django 4.2.5 on 2023-12-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_carrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='libro',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
